version: "3.7"

services:
  mssql:
    container_name: mssql_dev
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - 1433:1433
    volumes:
      - ./dbdata:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyPass@word
      - MSSQL_PID=Developer
    restart: unless-stopped
