version: '3.7'
services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_URLS: http://+:5000
    depends_on:
      - db
    networks:
      - my_network
    restart: unless-stopped
  db:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyPass@word
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - ./dbdata:/var/opt/mssql/data
    networks:
      - my_network
    restart: unless-stopped
networks:
  my_network:
